description: 'Notify on actions status'

inputs:
  webhook:
    description: 'Slack webhook URL'
    required: true

name: Notify Github Actions status

runs:
  steps:
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v3.0.3
      with:
        payload: |
          {
            "text": "Job ${{ github.job }} in workflow ${{ github.workflow }} of ${{ github.repository }} status ${{ job.status }}\nDetails at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "username": "GitHub"
          }
        webhook: ${{ inputs.webhook }}
        webhook-type: incoming-webhook
  using: composite
