jobs:
  create-snapshot:
    if: ${{ github.event.pull_request.merged }} == 'true'
    name: Create Mainfork Snapshot
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: get-proposal-count-difference
        name: Get Proposals Count Difference
        run: |
          #! /bin/bash
          set -o errexit -o errtrace -o xtrace

          PRE_MERGE_COMMIT="${{ github.event.pull_request.base.sha }}"

          get_number_of_proposals() {
            find 'proposals' -maxdepth 1 -mindepth 1 -type d | \
            while read directory
            do
                if find "$directory" -type f | grep --silent .
                then
                    echo "$directory"
                fi
            done |
            wc --lines
          }

          current_count="$(get_number_of_proposals)"
          git checkout "$PRE_MERGE_COMMIT"
          previous_count="$(get_number_of_proposals)"
          echo "DIFFERENCE=$((current_count - previous_count))" >> $GITHUB_OUTPUT

      - name: Script
        run: |
          #! /bin/bash
          set -o errexit -o errtrace -o xtrace

          echo "difference value: ${{ steps.get-proposal-count-difference.outputs.DIFFERENCE }}"

          if test "${{ steps.get-proposal-count-difference.outputs.DIFFERENCE }}" -gt "0"
          then
            echo "actual difference of: ${{ steps.get-proposal-count-difference.outputs.DIFFERENCE }}"
          fi

name: Create Mainfork Snapshot

on:
  pull_request:
    branches:
      - main
    types:
      - closed
